services:
  db:
    image: postgres:13.7
    container_name: geneatree-pg
    env_file:
      - ./.envs/.env-dev
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", ""]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    restart: always
    container_name: geneatree-nginx
    ports:
      - "8000:80"
    depends_on:
      - api
      - db
      - frontend

  api:
    build: api/
    container_name: geneatree-api
    env_file:
      - ./.envs/.env-dev
    volumes:
      - ./api/:/usr/app/
    depends_on:
      db:
        condition: service_healthy
    entrypoint: |
      bash -c "
        python3 manage.py makemigrations --no-input &&
        python3 manage.py migrate --no-input && 
        python3 manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: geneatree/
      dockerfile: Dockerfile.dev
    container_name: geneatree-frontend
    environment:
      - WATCHPACK_POLLING=true # true for autoreloading on Windows
    volumes:
      - ./geneatree/src/:/usr/app/src/
      - ./geneatree/public/:/usr/app/public/
      - ./geneatree/package.json:/usr/app/package.json
      - ./geneatree/package-lock.json:/usr/app/package-lock.json
